/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BridgeV2Abi__factory } from "./BridgeV2Abi__factory";
export { Erc20Abi__factory } from "./Erc20Abi__factory";
